# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Μνεία
email: marios@mneia.gr
description: >- # this means to ignore newlines until "baseurl:"
  Πρόσωπα, έργα, βιβλία, περιοδικά.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Mneia_GR
github_username:  mneia-gr

# Build settings
theme: mneia-theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

permalink: /:year/:month/:day/:title/

collections_dir: collections

collections:
  people:
    output: true
  magazines:
    output: true
  magazine-issues:
    output: true
  photographs:
    output: true
  works:
    output: true
  books:
    output: true
  publishers:
    output: true

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "person"
  - scope:
      path: ""
      type: "magazines"
    values:
      layout: "magazine"
  - scope:
      path: ""
      type: "magazine-issues"
    values:
      layout: "magazine-issue"
  - scope:
      path: ""
      type: "photographs"
    values:
      layout: "photograph"
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - scope:
      path: ""
      type: "publishers"
    values:
      layout: "publisher"

destination: "/home/m/Mneia/mneia-gr"
keep_files:
  - ".git"
  - README.md
  - CNAME
